name: dbt Databricks Deployment

on:
  push:
    branches:
      - dev
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt with Databricks adapter
        run: |
          pip install --upgrade pip
          pip install dbt-databricks

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_sales_db:
            target: ${{ github.ref_name }}
            outputs:
              dev:
                type: databricks
                catalog: ${{ secrets.DATABRICKS_CATALOG_DEV }}
                schema: ${{ secrets.DATABRICKS_SCHEMA_DEV }}
                host: ${{ secrets.DATABRICKS_HOST_DEV }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH_DEV }}
                token: ${{ secrets.DATABRICKS_TOKEN_DEV }}
              test:
                type: databricks
                catalog: ${{ secrets.DATABRICKS_CATALOG_TEST }}
                schema: ${{ secrets.DATABRICKS_SCHEMA_TEST }}
                host: ${{ secrets.DATABRICKS_HOST_TEST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH_TEST }}
                token: ${{ secrets.DATABRICKS_TOKEN_TEST }}
          EOF

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt seed
        run: dbt seed --target ${{ github.ref_name }}

      - name: Run dbt models
        run: dbt build --target ${{ github.ref_name }}

      - name: Run dbt tests
        run: dbt test --target ${{ github.ref_name }}
